[DF] Low Priority Fixes
impactMarket/app pull request #224
Opened 2022-07-20 21:07 UTC by hugomarquesdev

2022-07-21 08:22 UTC, obernardovieira commented on src/views/Notifications.tsx
> +            }
https://stackoverflow.com/a/13207939 ☺️

2022-07-21 21:15 UTC, hugomarquesdev commented on src/views/Notifications.tsx
> +            }
thanks for the tip! 😄

2022-07-22 14:55 UTC, obernardovieira requested changes
* If the ambassador is also a manager, it doesn't see the ambassador menu options such as community requests. Test account Ambassador 1 has that issue.
* Beneficiary sees both countdown and no funds warning. The no funds warning should be at the top of the page if the countdown is active. See design.
* Test account Council member 2, that is also ambassador and manager, doesn't see council member pages on sidebar, neither ambassador, only manager

2022-07-22 15:02 UTC, hugomarquesdev commented
> * If the ambassador is also a manager, it doesn't see the ambassador menu options such as community requests. Test account Ambassador 1 has that issue.
> * Beneficiary sees both countdown and no funds warning. The no funds warning should be at the top of the page if the countdown is active. See design.
> * Test account Council member 2, that is also ambassador and manager, doesn't see council member pages on sidebar, neither ambassador, only manager

@obernardovieira 
- the sidebar bugs are fixed on the high priority fixes PR that isn't yet merged.
- i'll fix the countdown + no funds, didn't check design, sorry 😅

2022-07-26 20:14 UTC, obernardovieira requested changes
I did a claim with "beneficiary 4" https://alfajores-blockscout.celo-testnet.org/tx/0xea16720c247f1a73f9f5e8d352d7ac04847d245e75acdca76d5bbb4ce9ce84ff/token-transfers. As beneficiary I see the community has no funds, but i don't see any countdown.

2022-07-26 21:01 UTC, hugomarquesdev commented
> I did a claim with "beneficiary 4" https://alfajores-blockscout.celo-testnet.org/tx/0xea16720c247f1a73f9f5e8d352d7ac04847d245e75acdca76d5bbb4ce9ce84ff/token-transfers. As beneficiary I see the community has no funds, but i don't see any countdown.

@obernardovieira 
from the devs call we've made I understood that if the community has no funds it doesn't know when it will have funds again. it can be days, weeks, etc... when that happens, the user has no countdown. 

basically what I understood was:
`hasFunds` and `isClaimable`: show claim btn
`hasFunds` and `isClaimable: false`: show countdown
`hasFunds: false`: doesn't show countdown (whether `isClaimable` is true or not) because even if `isClaimable` is true there are no funds, so, the beneficiary cant claim even when the countdown ends

from what you've commented, you want to show the countdown when `hasfunds: false `and `isClaimable: true` (the community has no funds)?

sorry for the long message and for my misconception once again 😣

2022-07-27 13:55 UTC, psoaresbj commented on src/components/UserMenu.tsx
> +import _ from 'lodash';
```suggestion
import kebabCase from 'lodash/kebabCase';
```

2022-07-27 13:55 UTC, psoaresbj commented on src/components/UserMenu.tsx
> +                    const roleKebabCase = _.kebabCase(role);
```suggestion
                    const roleKebabCase = kebabCase(role);
```

2022-07-27 14:02 UTC, psoaresbj approved these changes

2022-07-27 14:03 UTC, merged