Bugfix/dogfooding fixes
impactMarket/app pull request #261
Opened 2022-08-16 20:16 UTC by PauloSousapt

This PR fixes #<issue-number>

## Tests

- [ ] Tested on mobile
- [ ] Tested on dektop

This PR should be manually tested by @<manual-tester>, included on reviewers.

PS: This PR needs to be merged after the backend state update in Beneficiares/Managers

2022-08-16 20:31 UTC, hugomarquesdev requested changes

2022-08-16 20:31 UTC, hugomarquesdev commented on src/components/Table.tsx
>      refresh?: Date;
sort

2022-08-16 20:31 UTC, hugomarquesdev commented on src/views/Beneficiaries/index.tsx
> +    console.log(data?.beneficiaryEntities?.length);
👀

2022-08-17 09:53 UTC, psoaresbj approved these changes

2022-08-17 09:53 UTC, psoaresbj commented on src/components/Table.tsx
> +    callback?: Function;
sort

2022-08-17 09:53 UTC, psoaresbj commented on src/components/Table.tsx
> +    const { columns, callback, callbackProps, itemsPerPage, refresh, prefix, ...forwardProps } = props;
sort

2022-08-17 09:53 UTC, psoaresbj commented on src/hooks/useBeneficiaries.ts
> +
remove ln

2022-08-17 09:53 UTC, psoaresbj commented on src/hooks/useBeneficiaries.ts
> +
remove ln

2022-08-17 09:53 UTC, psoaresbj commented on src/modals/Contribute.tsx
> +                        // type="numeric"   ADD support for numeric keyboard on UI
dead code?

2022-08-17 09:53 UTC, psoaresbj commented on src/views/Communities/Community.tsx
> +                            { community.city.length > 19 ? `${community.city.substring(0, 19)}...` : community.city }
trim white spaces

2022-08-17 10:16 UTC, hugomarquesdev approved these changes

2022-08-17 10:21 UTC, merged