Add edit community details, contract and management
impactMarket/app pull request #279
Opened 2022-09-09 18:54 UTC by PauloSousapt

This PR fixes #<issue-number>

## Tests

- [ ] Tested on mobile
- [ ] Tested on dektop

This PR should be manually tested by @<manual-tester>, included on reviewers.

2022-09-12 11:51 UTC, obernardovieira requested changes
![image](https://user-images.githubusercontent.com/19441097/189642936-8df8385d-68ec-44fe-9be9-cc6790644818.png)

I tried to lock a community
1. Should be using the "Save changes" & "Cancel" as per design (like image above). (while transactions was pending, I didn't know what was happening)
2. I locked a community and it disappeared. It should still be visible and have a warning on the community page instead (see on donor view)

2022-09-21 18:28 UTC, obernardovieira reviewed
UI and functionality is perfect. But for some reasons, I save changes, says saved, but then on the community page nothing changed. Not sure if it's local cache or actually not saving

2022-09-21 20:23 UTC, PauloSousapt commented
> UI and functionality is perfect. But for some reasons, I save changes, says saved, but then on the community page nothing changed. Not sure if it's local cache or actually not saving

Will double check tomorrow, last time i've tested it, all was working properly.

2022-09-23 15:28 UTC, obernardovieira approved these changes

2022-09-30 09:17 UTC, hugomarquesdev approved these changes

2022-09-30 09:30 UTC, merged