New Logo
impactMarket/app pull request #281
Opened 2022-09-13 13:36 UTC by hugomarquesdev

This PR fixes #<issue-number>

## Tests

- [ ] Tested on mobile
- [ ] Tested on dektop

This PR should be manually tested by @obernardovieira @PauloSousapt @psoaresbj , included on reviewers.

2022-09-13 15:32 UTC, obernardovieira requested changes
everything, please

![image](https://user-images.githubusercontent.com/19441097/189944003-d9f6d0e4-17c8-411d-b40f-7f5cfe10dff1.png)

2022-09-14 18:58 UTC, hugomarquesdev commented
> everything, please
> 
> ![image](https://user-images.githubusercontent.com/19441097/189944003-d9f6d0e4-17c8-411d-b40f-7f5cfe10dff1.png)

UI PR: https://github.com/impactMarket/ui/pull/148

2022-09-15 12:22 UTC, obernardovieira approved these changes

2022-09-15 16:52 UTC, PauloSousapt approved these changes

2022-09-21 18:20 UTC, merged