Ambassador Edit Button Fix
impactMarket/app pull request #412
Opened 2023-02-27 12:46 UTC by hugomarquesdev

This PR fixes #402 

## Changes

- Fix: not showing edit button for ambassadors

## Tests

- [ ] Tested on mobile
- [ ] Tested on dektop

This PR should be manually tested by @obernardovieira @PauloSousapt , included on reviewers.

2023-03-10 12:13 UTC, Marianavpt commented
https://docs.google.com/presentation/d/1ABFPiZftuSTqWma8ZleyRQV7acORQXUB1PxRLhl_9gg/edit#slide=id.g218b5c6fc05_0_101

2023-03-14 15:44 UTC, obernardovieira requested changes
Correct for existing communities. but when trying to edit a pending claimed community, doesn't load contract data.

Eg: https://app-git-fix-ambassador-edit-button-ipct.vercel.app/communities/edit/7394 using Ambassador 3 demo account

2023-03-20 14:12 UTC, obernardovieira approved these changes

2023-03-22 16:13 UTC, PauloSousapt approved these changes

2023-03-23 18:22 UTC, obernardovieira commented
> If you need me to test this PR please tag me when needed

All good. A button was missing, but the functionality was there. All good.

2023-03-23 18:23 UTC, merged