Fixes: Microcredit Repayment
impactMarket/app pull request #460
Opened 2023-05-15 16:56 UTC by hugomarquesdev

## Changes

- Thinner table rows
- Translations
- New column: Last Repayment
- Small fixes

## Tests

- [x] Tested on mobile
- [x] Tested on dektop

This PR should be manually tested by @obernardovieira @PauloSousapt , included on reviewers.

2023-05-16 08:52 UTC, obernardovieira requested changes
![image](https://github.com/impactMarket/app/assets/19441097/25db3f5d-4bf8-48d8-a720-9c4297aea1c1)

without any last repayment I think the amount should be none as well or --

2023-05-16 16:25 UTC, hugomarquesdev commented
> ![image](https://user-images.githubusercontent.com/19441097/238589391-25db3f5d-4bf8-48d8-a720-9c4297aea1c1.png)
> 
> without any last repayment I think the amount should be none as well or --



> ![image](https://user-images.githubusercontent.com/19441097/238589391-25db3f5d-4bf8-48d8-a720-9c4297aea1c1.png)
> 
> without any last repayment I think the amount should be none as well or --

@obernardovieira fixed

2023-05-17 09:48 UTC, obernardovieira approved these changes
🥳

2023-05-18 16:37 UTC, PauloSousapt approved these changes

2023-05-19 21:19 UTC, merged