Feature/loan rejected view
impactMarket/app pull request #484
Opened 2023-06-20 14:47 UTC by marcusats

This PR fixes #468 

## Changes

- 

## Tests

- [ ] Tested on mobile
- [ ] Tested on dektop

This PR should be manually tested by @obernardovieira @PauloSousapt @hugomarquesdev , included on reviewers.

2023-06-20 16:15 UTC, hugomarquesdev requested changes

2023-06-20 16:15 UTC, hugomarquesdev commented on src/views/MicroCredit/LoanRejected.tsx
> +                    }}
Here you can use the props `padding`, `backgroundColor` and `borderRadius` outside of style, like so:
````
<Box
   ...
   padding={2}
   backgroundColor={colors.g100}
   borderRadius={0.5}
   style={{
      flexBasis: '65%',
      justifyContent: 'space-evenly',
   }}
>

2023-06-20 16:15 UTC, hugomarquesdev commented on src/views/MicroCredit/LoanRejected.tsx
> +export default LoanRejected;
Missing blank line at the end of the file

2023-06-20 16:15 UTC, hugomarquesdev commented on src/views/MicroCredit/index.tsx
> +export default MicroCredit;
Missing blank line at the end of the file

2023-06-21 11:15 UTC, obernardovieira approved these changes

2023-06-21 11:21 UTC, hugomarquesdev approved these changes

2023-06-26 11:49 UTC, PauloSousapt approved these changes

2023-06-26 15:40 UTC, merged