completing merge
impactMarket/app pull request #492
Opened 2023-07-13 04:26 UTC by marcusats

This PR fixes #467 

## Changes

- 

## Tests

- [ ] Tested on mobile
- [ ] Tested on dektop

This PR should be manually tested by @obernardovieira @hugomarquesdev @PauloSousapt , included on reviewers.

2023-07-13 16:36 UTC, hugomarquesdev commented
@marcusats eslint new error:
```
yarn run v1.22.19
$ /home/circleci/project/node_modules/.bin/tsc
src/views/MicrocreditManager/RequestTab/RequestList.tsx:360:22 - error TS6133: 'data' is declared but its value is never read.

360             render: (data : any) => (
                         ~~~~


Found 1 error in src/views/MicrocreditManager/RequestTab/RequestList.tsx:360

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 2
CircleCI received exit code 2
```

2023-07-13 16:49 UTC, hugomarquesdev commented
@marcusats new lint errors:
```
#!/bin/bash -eo pipefail
yarn eslint:dryrun
yarn run v1.22.19
$ eslint "./**/*.{ts,tsx}" --max-warnings=0

/home/circleci/project/src/views/MicrocreditManager/RequestTab/RequestList.tsx
  34:1   error    Imports should be sorted alphabetically  sort-imports-es6-autofix/sort-imports-es6
  34:10  warning  'da' is defined but never used           @typescript-eslint/no-unused-vars

✖ 2 problems (1 error, 1 warning)
  1 error and 0 warnings potentially fixable with the `--fix` option.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 1
CircleCI received exit code 1
```

Have you tried to run `yarn lint` or `yarn eslint:dryrun`? these are all lint errors.
Anyway vscode should warn you automatically when there are these errors 🤔

2023-07-13 21:59 UTC, hugomarquesdev requested changes

2023-07-13 21:59 UTC, hugomarquesdev commented on src/modals/Microcredit/AddNote.tsx
> +    console.log("Describe",describeConvBorrower);
👀

2023-07-13 21:59 UTC, hugomarquesdev commented on src/modals/Microcredit/AddNote.tsx
> +export default AddNote;
missing an empty line on the end of the file

2023-07-13 21:59 UTC, hugomarquesdev commented on src/hooks/useMicrocreditApplications.tsx
> +}
missing an empty line on the end of the file

2023-07-13 21:59 UTC, hugomarquesdev commented on src/components/FlexibleTab.tsx
> +export { FlexibleTab };
missing an empty line on the end of the file

2023-07-13 21:59 UTC, hugomarquesdev commented on src/modals/Microcredit/ApproveLoan.tsx
> +export default ApproveLoan;
missing an empty line on the end of the file

2023-07-13 21:59 UTC, hugomarquesdev commented on src/views/MicrocreditManager/BorrowersTab/BorrowersList.tsx
> +export default BorrowersList;
missing an empty line on the end of the file

2023-07-13 21:59 UTC, hugomarquesdev commented on src/views/MicrocreditManager/BorrowersTab/index.tsx
> +export default BorrowersTab;
missing an empty line on the end of the file

2023-07-13 21:59 UTC, hugomarquesdev commented on src/views/MicrocreditManager/RequestTab/RequestList.tsx
> +export default RequestList;
missing an empty line on the end of the file

2023-07-13 21:59 UTC, hugomarquesdev commented on src/views/MicrocreditManager/RequestTab/index.tsx
> +export default RequestTab;
missing an empty line on the end of the file

2023-07-14 09:51 UTC, obernardovieira approved these changes

2023-07-14 10:29 UTC, hugomarquesdev approved these changes

2023-07-14 10:32 UTC, merged