Fix: Require Signature to login + Notifications
impactMarket/app pull request #497
Opened 2023-07-25 10:26 UTC by hugomarquesdev

This PR fixes #<issue-number>

## Changes

- 

## Tests

- [ ] Tested on mobile
- [ ] Tested on dektop

This PR should be manually tested by @obernardovieira @PauloSousapt , included on reviewers.

2023-07-25 10:37 UTC, obernardovieira requested changes
1. The "expiry" on the signature, should be the date when the signature expires, not the current timestamp, or, it will be immediately invalid. Put 45 days in the future.

2. I'm getting a 404 when opening the notifications page.

2023-07-26 09:05 UTC, hugomarquesdev commented
> 

fixed 👌

2023-07-26 10:43 UTC, PauloSousapt approved these changes

2023-07-26 10:55 UTC, obernardovieira approved these changes

2023-07-26 10:55 UTC, merged