communication history + adding notes
impactMarket/app pull request #518
Opened 2023-08-18 15:12 UTC by marcusats

This PR fixes #477 

## Changes

- 

## Tests

- [ ] Tested on mobile
- [ ] Tested on dektop

This PR should be manually tested by @hugomarquesdev @obernardovieira @PauloSousapt , included on reviewers.

2023-08-18 16:08 UTC, obernardovieira reviewed
The fonts seems fairly small to me, specially the loan manager name and address. Is it correct?
![image](https://github.com/impactMarket/app/assets/19441097/caed2059-753d-4d32-915b-2db682e73fdf)

2023-08-21 10:29 UTC, obernardovieira requested changes
When clicking the address below the loan manager name, it doesn't do anything. It should show the same options as the other addresses (open in explore & copy). I think it's a generic component

2023-08-22 08:13 UTC, obernardovieira commented
👏  looks great :)

2023-08-22 08:58 UTC, hugomarquesdev requested changes

2023-08-22 08:58 UTC, hugomarquesdev commented on src/hooks/useAddNote.ts
> +export default useAddNote;
need blank line

2023-08-22 08:58 UTC, hugomarquesdev commented on src/hooks/useUserInfo.ts
> +export default useUserInfo;
need blank line

2023-08-22 08:58 UTC, hugomarquesdev commented on src/views/MicrocreditManager/ApproveRejectTab/BorrowersList.tsx
>                          title: 'Loan Application'
use `loanApplication` from `extractFromView('messages')`

2023-08-22 08:58 UTC, hugomarquesdev commented on src/views/User/Microcredit/CommunicationHistory/ManagerNote.tsx
> +    const {} = extractFromView('messages') as any;
is this needed?

2023-08-22 08:58 UTC, hugomarquesdev commented on src/views/User/Microcredit/CommunicationHistory/index.tsx
> +                                nextLabel="Next"
use `nextLabel={t('next')}`

2023-08-22 08:58 UTC, hugomarquesdev commented on src/views/User/Microcredit/CommunicationHistory/index.tsx
> +                                previousLabel="Previous"
use `previousLabel={t('previous')}`

2023-08-22 08:58 UTC, hugomarquesdev commented on src/views/User/Microcredit/index.tsx
> +                            Add Note
use `addNote` from `extractFromView('microcredit')`

2023-08-22 08:58 UTC, hugomarquesdev commented on src/views/User/Microcredit/index.tsx
> +export default Microcredit;
need blank line

2023-08-23 09:51 UTC, hugomarquesdev approved these changes

2023-08-25 12:12 UTC, merged